# Generated by Django 5.1.6 on 2025-04-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0003_activity_celebrity_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='activities',
            field=models.ManyToManyField(to='celebs.activity'),
        ),
    ]
