# Generated by Django 5.1.6 on 2025-04-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0005_remove_celebrity_date_seen_remove_celebrity_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='date_seen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CelebritySighting',
        ),
    ]
