# Generated by Django 5.1.6 on 2025-04-15 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0006_celebrity_date_seen_celebrity_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrity',
            name='date_seen',
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='location',
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='notes',
        ),
        migrations.CreateModel(
            name='CelebritySighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seen', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='celebs.celebrity')),
            ],
        ),
    ]
