# Generated by Django 5.1.6 on 2026-02-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(max_length=300)),
                ('description', models.TextField()),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('github_url', models.URLField(blank=True)),
                ('technologies', models.CharField(help_text='Ex: C++, Python, Django, IA', max_length=200)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
