# Generated by Django 5.1.6 on 2026-02-03 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_category_alter_project_options_project_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('logo', models.ImageField(help_text="Logo circulaire de l'établissement (PNG recommandé)", upload_to='institutions/')),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='is_research',
            field=models.BooleanField(default=False, help_text="Cocher si c'est un projet de recherche"),
        ),
        migrations.AlterField(
            model_name='project',
            name='pdf_report',
            field=models.FileField(blank=True, help_text='(Déprécié - Utilisez ProjectMedia à la place)', null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='project',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Établissement où le projet a été réalisé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.institution'),
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('pdf', 'PDF')], help_text='Type de fichier', max_length=10)),
                ('file', models.FileField(help_text='Fichier image, vidéo ou PDF', upload_to='project_media/')),
                ('caption', models.CharField(blank=True, help_text='Légende optionnelle', max_length=200)),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='portfolio.project')),
            ],
            options={
                'verbose_name_plural': 'Project Media',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
