# Generated by Django 5.1.6 on 2026-02-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_institution_project_is_research_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pdf_report',
        ),
    ]
