# Generated by Django 5.1.6 on 2026-02-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_project_pdf_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_en',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_fr',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_en',
            field=models.CharField(help_text='Ex: C++, Python, Django, IA', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_fr',
            field=models.CharField(help_text='Ex: C++, Python, Django, IA', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectmedia',
            name='caption_en',
            field=models.CharField(blank=True, help_text='Légende optionnelle', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectmedia',
            name='caption_fr',
            field=models.CharField(blank=True, help_text='Légende optionnelle', max_length=200, null=True),
        ),
    ]
